#!/bin/bash

# Run make to build the project
make

# Check if the last executable exists
if [ -f build/last ]; then
    # Make the last executable runnable
    chmod +x build/last
    printf "\nRunning Last\n"

    # Run the last executable
    ./build/last
else
    echo "Error: 'last' executable not found."
fi
